name: Bale Bot

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
        run: |
          python app.py
